### ISSUE TITLE
I have the proper file path, Valencia is telling me it cant open file location

### ISSUE THREAD

**Issue by SudoDare** [orange-cpp/valencia#2]
I went into steam, clicked apex and browsed local files for the game. Took the file path from there..
Valencia opens, but just tells me this error even though im putting my file path to R5apex.exe

Error Code:
"Cannot open file, try to check if path is valid"

Discord:
Sudo1337.

with the "."

**Comment by orange-cpp** [comment]
Hello, would you kindly to tell how you entered path using command line:
./valencia "path/to/apex" or ./valencia path/to/apex

If path to apex contains spaces you must, wrap it in double quotes.  Let me know if it fixed your problem!

**Comment by orange-cpp** [comment]
Accidentally closed issue
